package com.mediconnect.user.enums;

public enum Specialization {
    GENERAL_PHYSICIAN, CARDIOLOGIST, NEUROLOGIST,
    DERMATOLOGIST, ORTHOPEDIC, PEDIATRICIAN,
    GYNECOLOGIST, PSYCHIATRIST, OPHTHALMOLOGIST,
    ENT_SPECIALIST, DIABETOLOGIST, ONCOLOGIST
}